apiVersion: apps/v1
kind: Deployment
metadata:
  name: FoodStore
  labels:
    app: FoodStore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FoodStore
  template:
    metadata:
      labels:
        app: FoodStore
    spec:
      containers:
        - name: FoodStore
          image: username/FoodStore:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
